# in .cargo/config.toml

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "canton.json"

# in Cargo.toml

[dependencies]
bootloader = "0.9.23"